# Generated by Django 5.2.8 on 2025-12-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customuser_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
